### ISSUE TITLE
!200 results in run termination

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/grab-typings#13]
C:\Users\begreen\git\foundry-ts>gt
Oops - something went wrong... 404

**Comment by bengreenier** [comment]
referenced the v1.1.7 change that cause this to surface more than in the original commit - see comments in `3411ffe`.

looks like a code change in v1.1.7 results in `!200` statuses exiting the entire run - this should be fixed, clearly.

**Comment by bengreenier** [comment]
referenced the original change that caused this bug at all - see comments in `ea1e414`.

oh okay - looks like v1.1.7 is just surfacing the bug more often since we're now hunting for many more deps (since #4) that may not exist.

**Comment by bengreenier** [comment]
@benfahrenheit - if you're looking to contribute more goodies, this is high impact.

**Comment by benferse** [comment]
Hit this for the first time tonight myself. Small world.

**Comment by bengreenier** [comment]
fixed in `v1.1.10` on npm.
