### ISSUE TITLE
--version always returning 'unknown'

### ISSUE THREAD

**Issue by benferse** [bengreenier/grab-typings#5]
Seen on a Windows install, with grab-typings installed as a global package:

```
C:\> gt --version
unknown
```

Seems the version finder isn't quite janky enough. At least on Windows, the relative path references in GrabTypings() will resolve against the dir where you launched gt, not the script dir. No package.json for you.

**Comment by bengreenier** [comment]
sounds like we probably want `__dirname` in those relatives paths

**Comment by benferse** [comment]
Yeah, otherwise it's optionally messing with process.argv[1] iff platform == "win32", and ew.

**Comment by bengreenier** [comment]
thanks @benfahrenheit
